export enum UploadURLS {
  news = '/uploads/image/news',
  avatar = '/uploads/image/avatar',
  gallery = '/uploads/image/gallery',
  delete_folder = '/uploads/folder-delete',
}
export const API_URLs = [
  '/admin/news',
  '/admin/article',
  '/admin/article-update',
  '/admin/article-add',
  '/admin/article-delete',
  '/admin/login',
  '/api/categories',
  '/admin/category',
  '/admin/category-update',
  '/admin/category-add',
  '/admin/category-delete',
  '/admin/check',
  '/admin/files',
  '/admin/user-update',
  '/uploads/image-delete',
  UploadURLS.news,
  UploadURLS.avatar,
  UploadURLS.gallery,
  UploadURLS.delete_folder,
] as const
