export enum UploadURLS {
  news = '/image-news',
  avatar = '/image-avatar',
  gallery = '/image-gallery',
  delete_image = '/image-delete',
  delete_folder = '/folder-delete',
}
// export const API_URLs = [
//   '/api/v1/dashboard/news',
//   '/api/v1/dashboard/article',
//   '/api/v1/dashboard/article-update',
//   '/api/v1/dashboard/article-add',
//   '/api/v1/dashboard/article-delete',
//   '/api/v1/dashboard/login',
//   '/api/v1/dashboard/categories',
//   '/api/v1/dashboard/category',
//   '/api/v1/dashboard/category-update',
//   '/api/v1/dashboard/category-add',
//   '/api/v1/dashboard/category-delete',
//   '/api/v1/dashboard/check',
//   '/api/v1/dashboard/user-update',
//   '/files',
//   '/uploads/image-delete',
//   UploadURLS.news,
//   UploadURLS.avatar,
//   UploadURLS.gallery,
//   UploadURLS.delete_folder,
// ] as const
